version: '3.8'
services:
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    environment:
      - RUNNING_IN_DOCKER=true
    ports:
      - "3001:3001"
    restart:
      always
    links:
      - server
  server:
    image: server
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    restart:
      always

