name: Lint and Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm ci --prefix frontend

    - name: Lint
      
      run: npm run lint --prefix frontend

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm ci --prefix backend

    - name: Build Backend
      run: npm run build --prefix backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm ci --prefix frontend

    - name: Build Frontend
      run: npm run build --prefix frontend